ALTER TABLE usuarios MODIFY COLUMN nome VARCHAR(100) NULL;
ALTER TABLE usuarios MODIFY COLUMN email VARCHAR(120) NULL;
ALTER TABLE usuarios MODIFY COLUMN senha VARCHAR(255) NULL;
ALTER TABLE usuarios MODIFY COLUMN telefone VARCHAR(14) NULL;
ALTER TABLE usuarios MODIFY COLUMN perfil VARCHAR(30) NULL;
